import "../style/globals.css";
import "../style/index.scss";
import AppProvider from "@/contextApi/AppProvider";
import MouseCursor from "@/utils/MouseCursor";
import WrapperCommon from "@/layout/WrapperCommon";
import HeaderTwo from "@/layout/header/HeaderTwo";
import Footer from "@/layout/footer/Footer";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import authOptions from "./api/auth/[...nextauth]/route";
import { ThemeProvider } from "./ThemeProvider";

export const metadata = {
  title: "Investor Radar",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          {/* <link rel="icon" href="/favicon.png" /> */}
          <link href="../style/globals.css" rel="stylesheet"></link>
          <link
            href="https://fonts.googleapis.com/css2?family=Archivo:wght@300;400;500;600;700;800&family=Barlow:wght@300;400;500;600;700;800&family=Gilda+Display&display=swap"
            rel="stylesheet"
          ></link>
        </head>

        <body>
          <SessionProvider session={session}>
            <AppProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
              >
              {/* <MouseCursor /> */}
              {children}
              </ThemeProvider>
            </AppProvider>
          </SessionProvider>
        </body>
      </html>
    </>
  );
}
